unit translator;
interface
uses windows, sysutils;

function translate_title(s:string) : string;
function get_stats_value( uitype : int64; dotr : boolean ): string;
function srep(s, sfrom, sto  : string) : string;
Function translate_type(s3:string):string;
Function translate_slot(s3:string):string;

implementation
uses unit1, d3ui;

function srep(s, sfrom, sto  : string) : string;
begin
  result := StringReplace(s, sfrom, sto, [rfReplaceAll, rfIgnoreCase]);
end;

function get_stats_value( uitype : int64; dotr : boolean ): string;
var s : string;
begin

  s := get_text_value2( uitype );
  if dotr then begin
    s := srep(s, ' к ', ' ');
    s := srep(s, 'критическому урону', 'critical damage');
    s := srep(s, 'сопротивлению всем стихиям', 'resistance to all elements');
    s := srep(s, 'вероятности критического удара', 'critical hit chance');
    s := srep(s, 'дополнительного опыта при убийстве монстров', ' to bonus experience');

    s := srep(s, 'ед. брони', 'armor');
    s := srep(s, 'Урон от атак ближнего боя уменьшен на', 'reduced melee damage');
    s := srep(s, 'Урон от атак дальнего боя уменьшен на', 'reduced ranged damage');

    s := srep(s, 'скорости атаки', 'attack speed');
    s := srep(s, 'сопротивлению огню', 'fire resist');
    s := srep(s, 'сопротивлению молнии', 'lightning resist');
    s := srep(s, 'сопротивлению яду', 'poison resist');
    s := srep(s, 'сопротивлению холоду', 'cold resist');
    s := srep(s, 'сопротивлению тайной магии', 'arcane resist');
    s := srep(s, 'сопротивлению физическому урону', 'physical resist');

    s := srep(s, 'ед. максимальному урону', 'maximum damage');
    s := srep(s, 'ед. минимальному урону', 'minimal damage');

    s := srep(s, 'скорости передвижения', 'move speed');


    s := srep(s, 'Восстанавливает ', 'Regenerates ');
    s := srep(s, 'ед. здоровья в сек.', 'life per second');
    s := srep(s, 'Атакующие в ближнем бою получают ', 'Melee attackers take ');
    s := srep(s, 'ед. урона за каждый удар', 'damage per hit');
    s := srep(s, 'Восполняет ', 'Restores ');
    s := srep(s, 'ед. здоровья при ударе', 'life on hit');
    s := srep(s, 'ед. здоровья при убийстве', 'life on kill');

    s := srep(s, 'вероятности блока', 'chance to block');
    s := srep(s, 'ед. урона от сил Света', 'Holy Damage');
    s := srep(s, 'ед. урона от огня', 'Fire Damage');
    s := srep(s, 'ед. урона от молнии', 'Lightning Damage');
    s := srep(s, 'ед. урона от тайной магии', 'Arcane Damage');
    s := srep(s, 'ед. урона от холода', 'Cold Damage');
    s := srep(s, 'ед. урона от яда', 'Poison Damage');
    s := srep(s, 'вероятности найти магический предмет', 'magic find');
    s := srep(s, 'золота при убийстве монстров', 'gold find');
    s := srep(s, 'ед. опыта при убийстве монстров', 'exp on monster kill');


    s := srep(s, 'Сферы здоровья дополнительно восполняют ', 'Health Globes Grant ');
    s := srep(s, 'Увеличивает радиус автоматического поднятия золота и сфер здоровья на ', 'Pickup radius is increased by ');
    s := srep(s, ' вероятность вызвать у цели кровотечение, наносящее ', ' chance to inflict bleed for ');
    s := srep(s, ' урона в течение ', ' damage over ');
    s := srep(s, 'вероятность отбросить цель при попадании', 'chance to knockback on hit');
    s := srep(s, ' от нанесенного урона преобразуется в здоровье', ' life leech');
    s := srep(s, 'Скорость восстановления ненависти повышается на ', 'Hatred regen increased by ');
    s := srep(s, ' ед. в сек', ' per sec');
    s := srep(s, ' ед. максимальному запасу магической энергии', ' to max arcane power');
    s := srep(s, 'Данный предмет не теряет прочности', 'Ignores durability loss');
    s := srep(s, 'ед. максимальному запасу концентрации', 'max concentration');
    s := srep(s, 'максимальному запасу маны', 'max mana');
    s := srep(s, 'Время действия эффектов контроля уменьшается на', 'The duration of control impairing effects reduced by');
    s := srep(s, 'Критические удары восстанавливают', 'Critical hits restore');
    s := srep(s, 'ед. магической энергии', 'arcane power');
    s := srep(s, ', наносимому особым противникам', ' to elites');
    s := srep(s, ', наносимому демонам', ' to demons');

    s := srep(s, 'Скорость восстановления духа повышается на', 'Spirit regen increased');
    s := srep(s, 'Требования уровню снижены на', 'Level requirements reduced by ');
    s := srep(s, 'Урон от атак особых противников уменьшен на', 'Damage from elites reduced by');
    s := srep(s, 'ед. максимальному запасу ярости', 'to max fury');
    s := srep(s, 'При нанесении урона вы можете обездвижить противников', 'Chance to Immobilize on Hit');

    s := srep(s, 'вероятность повергнуть цель в ужас при попадании', 'Chance to Fear on Hit');
    s := srep(s, 'вероятность замедлить цель при попадании', 'Chance to Slow on Hit');
    s := srep(s, 'вероятность вызвать у цели окоченение при попадании', 'Chance to Chill on Hit');
    s := srep(s, 'вероятность ослепить цель при попадании', 'Chance to Blind on Hit');
    s := srep(s, 'вероятность отбросить цель при попадании', 'Chance to Knockback on Hit');
    s := srep(s, 'вероятность обездвижить цель при попадании', 'Chance to Immobilize on Hit');
    s := srep(s, 'вероятность заморозить цель при попадании', 'Chance to Freeze on Hit');
    s := srep(s, 'вероятность оглушить цель при попадании', 'Chance to Stun on Hit');

    s := srep(s, 'вероятности при атаке выпустить огненный шар', 'chance to hurl a fireball on attack');
    s := srep(s, 'вероятности при атаке создать магическую сферу', 'chance to hurl a frozen orb when attacking');

    s := srep(s, 'Скорость восстановления маны повышается', 'mana regen increased');
    s := srep(s, 'за каждую затраченную единицу духа', 'per spirit spent');





    s := srep(s, 'от умения ', 'from skill ');
    s := srep(s, '«Хлещущий ветер»', '«Sweeping wind»');
    s := srep(s, '«Бросок болы»', '«Bola shot»');
    s := srep(s, '«Шипастая ловушка»', '«Spiked trap»');
s := srep(s, '«Сокрушающий удар»', '«Bash»');
s := srep(s, '«Молот Древних»', '«Hammer of the Ancients»');
s := srep(s, '«Рассекающий удар»', '«Cleave»');
s := srep(s, '«Топот»', '«Ground Stomp»');
s := srep(s, '«Рваные раны»', '«Rend»');
s := srep(s, '«Удар в прыжке»', '«Leap»');
s := srep(s, '«Копье Древних»', '«Ancient Spear»');
s := srep(s, '«Бешенство»', '«Frenzy»');
s := srep(s, '«Сейсмический удар»', '«Seismic Slam»');
s := srep(s, '«Отмщение»', '«Revenge»');
s := srep(s, '«Бросок оружия»', '«Weapon Throw»');
s := srep(s, '«Спринт»', '«Sprint»');
s := srep(s, '«Угрожающий крик»', '«Threatening Shout»');
s := srep(s, '«Землетрясение»', '«Earthquake»');
s := srep(s, '«Вихрь»', '«Whirlwind»');
s := srep(s, '«Яростный рывок»', '«Furious Charge»');
s := srep(s, '«Стойкость к боли»', '«Ignore Pain»');
s := srep(s, '«Боевая ярость»', '«Battle Rage»');
s := srep(s, '«Зов Древних»', '«Call of the Ancients»');
s := srep(s, '«Сверхсила»', '«Overpower»');
s := srep(s, '«Воинственный клич»', '«War Cry»');
s := srep(s, '«Гнев берсерка»', '«Wrath of the Berserker»');
s := srep(s, '«Отравленный дротик»', '«Poison Dart»');
s := srep(s, '«Объятия смерти»', '«Grasp of the Dead»');
s := srep(s, '«Трупные пауки»', '«Corpse Spiders»');
s := srep(s, '«Призыв псов-зомби»', '«Summon Zombie Dogs»');
s := srep(s, '«Огненные нетопыри»', '«Firebats»');
s := srep(s, '«Ужас»', '«Horrify»');
s := srep(s, '«Жатва душ»', '«Soul Harvest»');
s := srep(s, '«Нашествие жаб»', '«Plague of Toads»');
s := srep(s, '«Мстительный дух»', '«Haunt»');
s := srep(s, '«Жертвенный обряд»', '«Sacrifice»');
s := srep(s, '«Зомби-берсерк»', '«Zombie Charger»');
s := srep(s, '«Поступь духа»', '«Spirit Walk»');
s := srep(s, '«Призрачный шквал»', '«Spirit Barrage»');
s := srep(s, '«Громадень»', '«Gargantuan»');
s := srep(s, '«Рой саранчи»', '«Locust Swarm»');
s := srep(s, '«Огненная бомба»', '«Firebomb»');
s := srep(s, '«Сглаз»', '«Hex»');
s := srep(s, '«Едкое облако»', '«Acid Cloud»');
s := srep(s, '«Всеобщее помешательство»', '«Mass Confusion»');
s := srep(s, '«Большое страшное вуду»', '«Big Bad Voodoo»');
s := srep(s, '«Стена зомби»', '«Wall of Zombies»');
s := srep(s, '«Армия фетишей»', '«Fetish Army»');
s := srep(s, '«Кулаки грома»', '«Fists of Thunder»');
s := srep(s, '«Хвост дракона»', '«Lashing Tail Kick»');
s := srep(s, '«Касание смерти»', '«Deadly Reach»');
s := srep(s, '«Ослепляющая вспышка»', '«Blinding Flash»');
s := srep(s, '«Стремительность урагана»', '«Tempest Rush»');
s := srep(s, '«Дыхание небес»', '«Breath of Heaven»');
s := srep(s, '«Мощный рывок»', '«Dashing Strike»');
s := srep(s, '«Волна увечий»', '«Crippling Wave»');
s := srep(s, '«Волна Света»', '«Wave of Light»');
s := srep(s, '«Взрывное касание»', '«Exploding Palm»');
s := srep(s, '«Ураганный удар»', '«Cyclone Strike»');
s := srep(s, '«Путь Сотни Кулаков»', '«Way of the Hundred Fists»');
s := srep(s, '«Покой»', '«Serenity»');
s := srep(s, '«Семь сторон света»', '«Seven-Sided Strike»');
s := srep(s, '«Мантра уклонения»', '«Mantra of Evasion»');
s := srep(s, '«Хлещущий ветер»', '«Sweeping Wind»');
s := srep(s, '«Мантра воздаяния»', '«Mantra of Retribution»');
s := srep(s, '«Святая святых»', '«Inner Sanctuary»');
s := srep(s, '«Таинственный союзник»', '«Mystic Ally»');
s := srep(s, '«Мантра исцеления»', '«Mantra of Healing»');
s := srep(s, '«Мантра осуждения»', '«Mantra of Conviction»');
s := srep(s, '«Самонаводящаяся стрела»', '«Hungering Arrow»');
s := srep(s, '«Бросок кинжала»', '«Impale»');
s := srep(s, '«Замедляющий выстрел»', '«Entangling Shot»');
s := srep(s, '«Шипы»', '«Caltrops»');
s := srep(s, '«Скоростная стрельба»', '«Rapid Fire»');
s := srep(s, '«Дымовая завеса»', '«Smoke Screen»');
s := srep(s, '«Кульбит»', '«Vault»');
s := srep(s, '«Бросок болы»', '«Bola Shot»');
s := srep(s, '«Шакрам»', '«Chakram»');
s := srep(s, '«На изготовку»', '«Preparation»');
s := srep(s, '«Отход под прикрытием»', '«Evasive Fire»');
s := srep(s, '«Гранаты»', '«Grenades»');
s := srep(s, '«Сила тьмы»', '«Shadow Power»');
s := srep(s, '«Веер клинков»', '«Fan of Knives»');
s := srep(s, '«Шипастая ловушка»', '«Spike Trap»');
s := srep(s, '«Питомец»', '«Companion»');
s := srep(s, '«Обстрел»', '«Strafe»');
s := srep(s, '«Стрела стихий»', '«Elemental Arrow»');
s := srep(s, '«Метка смерти»', '«Marked for Death»');
s := srep(s, '«Залп»', '«Multishot»');
s := srep(s, '«Турель»', '«Sentry»');
s := srep(s, '«Разрывная стрела»', '«Cluster Arrow»');
s := srep(s, '«Ливень возмездия»', '«Rain of Vengeance»');
s := srep(s, '«Магическая стрела»', '«Magic Missile»');
s := srep(s, '«Морозный луч»', '«Ray of Frost»');
s := srep(s, '«Шоковый разряд»', '«Shock Pulse»');
s := srep(s, '«Кольцо льда»', '«Frost Nova»');
s := srep(s, '«Магическая сфера»', '«Arcane Orb»');
s := srep(s, '«Алмазная кожа»', '«Diamond Skin»');
s := srep(s, '«Силовая волна»', '«Wave of Force»');
s := srep(s, '«Призрачный клинок»', '«Spectral Blade»');
s := srep(s, '«Магический поток»', '«Arcane Torrent»');
s := srep(s, '«Энергетический вихрь»', '«Energy Twister»');
s := srep(s, '«Ледяной доспех»', '«Ice Armor»');
s := srep(s, '«Электрошок»', '«Electrocute»');
s := srep(s, '«Замедление времени»', '«Slow Time»');
s := srep(s, '«Доспех бури»', '«Storm Armor»');
s := srep(s, '«Энергетический взрыв»', '«Explosive Blast»');
s := srep(s, '«Магическое оружие»', '«Magic Weapon»');
s := srep(s, '«Гидра»', '«Hydra»');
s := srep(s, '«Расщепление»', '«Disintegrate»');
s := srep(s, '«Фамилиар»', '«Familiar»');
s := srep(s, '«Телепортация»', '«Teleport»');
s := srep(s, '«Зеркальное отражение»', '«Mirror Image»');
s := srep(s, '«Метеорит»', '«Meteor»');
s := srep(s, '«Снежная буря»', '«Blizzard»');
s := srep(s, '«Энергетический доспех»', '«Energy Armor»');
s := srep(s, '«Архонт»', '«Archon»');
    s := srep(s, 'Снижает затраты ресурсов на использованиe умения', 'Reduces cost of ');
    s := srep(s, '(только для охотников на демонов)', '(demon hunter only)');
    s := srep(s, '(только для чародеев)', '(wizards only)');
    s := srep(s, '(только для монахов)', '(monks only)');
    s := srep(s, '(только для колдунов)', '(WD only)');
    s := srep(s, '(только для варваров)', '(barbarians only)');


    s := srep(s, 'ловкости', 'dexterity');
    s := srep(s, 'ед. здоровья', 'life');
    s := srep(s, 'ед. урона', 'damage');
    s := srep(s, 'ед. ярости', 'fury');
    s := srep(s, 'ед. духа', 'spirit');
    s := srep(s, 'ед. ненависти', 'hatred');
    s := srep(s, 'ед. дисциплины', 'discipline');
    s := srep(s, 'ед. маны', 'mana');
    s := srep(s, 'ед. магической энергии', 'arcane power');
    s := srep(s, 'При получении урона вы можете применить заклинание', 'On recieving damage you can cast');
    s := srep(s, 'вероятности нанести критический удар умением', 'chance to crit with');





    s := srep(s, 'силе', 'strength');
    s := srep(s, 'живучести', 'vitality');
    s := srep(s, 'интеллекту', 'intelligence');
    s := srep(s, 'урону', 'damage');
    s := srep(s, '% здоровья', '% life');

    s := srep(s, 'Пустое гнездо', 'Empty');
    s := srep(s, ' на ', ' by ');
    s := srep(s, ' сек.', ' sec');
    s := srep(s, 'атак в sec', 'attacks per sec');
    s := srep(s, 'атаки в sec', 'attacks per sec');


  end;
  result := s;
end;


function translate_title(s:string) : string;
begin
s := srep(s, 'Костяная стена', 'Wall of Bone');
s := srep(s, 'Отпор', 'Denial');
s := srep(s, 'Центурион', 'Centurion');
s := srep(s, 'Недремлющий защитник', 'Lidless Wall');
s := srep(s, 'Башня из слоновой кости', 'Ivory Tower');
s := srep(s, 'Священный защитник', 'Hallowed Defender');
s := srep(s, 'Грозовой щит', 'Stormshield');
s := srep(s, 'Сломанная корона', 'Broken Crown');
s := srep(s, 'Корона Леорика', 'Leoric''s Crown');
s := srep(s, 'Воспоминания Декарда Каина', 'Cain''s Memory');
s := srep(s, 'Навершие Огильда', 'Aughild''s Peak');
s := srep(s, 'Слепая вера', 'Blind Faith');
s := srep(s, 'Гигантский череп', 'Giant Skull');
s := srep(s, 'Дальновидность Стража', 'Guardian''s Foresight');
s := srep(s, 'Лик Андариэль', 'Andariel''s Visage');
s := srep(s, 'Шлем командования', 'The Helm of Command');
s := srep(s, 'Вращающиеся камни мудреца', 'Sage''s Orbit');
s := srep(s, 'Сумеречная маска мемпо', 'Mempo of Twilight');
s := srep(s, 'Взор Наталии', 'Natalya''s Sight');
s := srep(s, 'Маска мудрости Тал Раши', 'Tal Rasha''s Guise of Wisdom');
s := srep(s, 'Триумф бессмертного короля', 'Immortal King''s Triumph');
s := srep(s, 'Не видеть зла', 'See No Evil');
s := srep(s, 'Гьяна на касу', 'Gyana Na Kashu');
s := srep(s, 'Глаз разума', 'The Mind''s Eye');
s := srep(s, 'Эрланг Шен', 'Erlang Shen');
s := srep(s, 'Безоаровый камень', 'Bezoar Stone');
s := srep(s, 'Око бури', 'The Eye of the Storm');
s := srep(s, 'Взгляд Тзо Крина', 'Tzo Krin''s Gaze');
s := srep(s, 'Камень безумия', 'Madstone');
s := srep(s, 'Сияние Инны', 'Inna''s Radiance');
s := srep(s, 'Расколотый клык', 'Split Tusk');
s := srep(s, 'Кетцалькоатль', 'Quetzalcoatl');
s := srep(s, 'Кровожадный оскал', 'The Grin Reaper');
s := srep(s, 'Тикланский лик', 'Tiklandian Visage');
s := srep(s, 'Лицо Гьюа', 'Visage of Giyua');
s := srep(s, 'Видение Зунимассы', 'Zunimassa''s Vision');
s := srep(s, 'Свами', 'The Swami');
s := srep(s, 'Колпак темного мага', 'Dark Mage''s Shade');
s := srep(s, 'Грозовой ворон', 'Storm Crow');
s := srep(s, 'Безнаказанность Борна', 'Born''s Impunity');
s := srep(s, 'Наплечные щитки города менял', 'Barter Town Pads');
s := srep(s, 'Правление Огильда', 'Aughild''s Reign');
s := srep(s, 'Стража Аширы', 'Asheara''s Guard');
s := srep(s, 'Мантия стража смерти', 'Death Watch Mantle');
s := srep(s, 'Семь грехов', 'Seven Sins');
s := srep(s, 'Полет демона', 'Demon''s Flight');
s := srep(s, 'Мерзкий страж', 'Vile Ward');
s := srep(s, 'Кираса Акилы', 'Aquila Cuirass');
s := srep(s, 'Стальное сердце Борна', 'Born''s Heart of Steel');
s := srep(s, 'Железное сердце', 'Heart of Iron');
s := srep(s, 'Кольчуга', 'Chaingmail');
s := srep(s, 'Владычество Огильда', 'Aughild''s Dominion');
s := srep(s, 'Золотая кожа', 'Goldskin');
s := srep(s, 'Пепельный мундир', 'Cindercoat');
s := srep(s, 'Одеяния ридраэлмов', 'Robes of the Rydraelm');
s := srep(s, 'Сердце демона', 'Demon''s Heart');
s := srep(s, 'Мощь Тираэля', 'Tyrael''s Might');
s := srep(s, 'Бесконечный простор Инны', 'Inna''s Vast Expanse');
s := srep(s, 'Беспрестанная погоня Тал Раши', 'Tal Rasha''s Relentless Pursuit');
s := srep(s, 'Вечное правление бессмертного короля', 'Immortal King''s Eternal Reign');
s := srep(s, 'Накидка Блекторна', 'Blackthorne''s Surcoat');
s := srep(s, 'Сущность Зунимассы', 'Zunimassa''s Marrow');
s := srep(s, 'Плащ Бекинсейл', 'Beckon Sail');
s := srep(s, 'Инквизитор', 'The Inquisitor');
s := srep(s, 'Объятия Наталии', 'Natalya''s Embrace');
s := srep(s, 'Меткие ударные пластины', 'Steady Strikers');
s := srep(s, 'Доспехи Гунгдо', 'Gungdo Gear');
s := srep(s, 'Оковы раба', 'Slave Bonds');
s := srep(s, 'Ультиматум Огильда', 'Aughild''s Ultimatum');
s := srep(s, 'Отражатель Стража', 'Guardian''s Deflector');
s := srep(s, 'Обещание славы', 'Promise of Glory');
s := srep(s, 'Удивительные отражатели', 'Wondrous Deflectors');
s := srep(s, 'Наручи силача', 'Strongarm Bracers');
s := srep(s, 'Месть демона', 'Demon''s Revenge');
s := srep(s, 'Лакуни-расхитители', 'Lacuni Prowlers');
s := srep(s, 'Магические кулаки', 'Magefist');
s := srep(s, 'Перчатки Декарда Каина для письма', 'Cain''s Scribe');
s := srep(s, 'Перехваты', 'Pendergrasps');
s := srep(s, 'Стальной кулак Аширы', 'Asheara''s Iron Fist');
s := srep(s, 'Каменные рукавицы', 'Stone Gauntlets');
s := srep(s, 'Рукавицы гладиатора', 'Gladiator Gauntlets');
s := srep(s, 'Рукавицы обжигающего холода', 'Frostburn Gauntlets');
s := srep(s, 'Жест мудреца', 'Sage''s Gesture');
s := srep(s, 'Таскер и Тео', 'Tasker and Theo');
s := srep(s, 'Латы бессмертного короля', 'Immortal King''s Irons');
s := srep(s, 'Ремень бдительности', 'Vigilante Belt');
s := srep(s, 'Пояс быстрой расправы', 'Quick Draw Belt');
s := srep(s, 'Атласный кушак капитана Кримсона', 'Captain Crimson''s Satin Sash');
s := srep(s, 'Златотканная перевязь', 'Goldwrap');
s := srep(s, 'Шафрановый кушак', 'Saffron Wrap');
s := srep(s, 'Пояс из ушей', 'String of Ears');
s := srep(s, 'Ангельская коса', 'Angel Hair Braid');
s := srep(s, 'Верные ножны Стража', 'Guardian''s Sheath');
s := srep(s, 'Ведьмин пояс', 'Hellcat Waistguard');
s := srep(s, 'Перевязь демона', 'Demon''s Lock');
s := srep(s, 'Колдовской час', 'The Witching Hour');
s := srep(s, 'Благосклонность Инны', 'Inna''s Favor');
s := srep(s, 'Пояс Блекторна с насечками', 'Blackthorne''s Notched Belt');
s := srep(s, 'Ремень Тал Раши', 'Tal Rasha''s Brace');
s := srep(s, 'Ремень великанов', 'Girdle of Giants');
s := srep(s, 'Признанный герой', 'The Undisputed Champion');
s := srep(s, 'Обвязка Котуура', 'Kotuur''s Brace');
s := srep(s, 'Гордость Кассия', 'Pride of Cassius');
s := srep(s, 'Наводящая ужас железная цепь', 'Dread Iron');
s := srep(s, 'Сила громовержца', 'Thunder God''s Vigor');
s := srep(s, 'Вечная мощь', 'Ageless Might');
s := srep(s, 'Стенания', 'Lamentation');
s := srep(s, 'Племенная повязка бессмертного короля', 'Immortal King''s Tribal Binding');
s := srep(s, 'Зачумленные штаны', 'Pox Faulds');
s := srep(s, 'Одежды Декарда Каина', 'Cain''s Robes');
s := srep(s, 'Бушприт капитана Кримсона', 'Captain Crimson''s Bowsprit');
s := srep(s, 'Штаны Хаммера', 'Hammer Jammers');
s := srep(s, 'Болотные штаны', 'Swamp Land Waders');
s := srep(s, 'Поступь Аширы', 'Asheara''s Gait');
s := srep(s, 'Штаны геенны', 'Gehennas');
s := srep(s, 'Чешуя демона', 'Demon''s Scale');
s := srep(s, 'Покорители подземных глубин', 'Depth Diggers');
s := srep(s, 'Турнирные кольчужные штаны Блекторна', 'Blackthorne''s Jousting Mail');
s := srep(s, 'Умеренность Инны', 'Inna''s Temperance');
s := srep(s, 'Очень простые сапоги', 'The Crudest Boots');
s := srep(s, 'Чулки Лута', 'Lut Socks');
s := srep(s, 'Сандалии Декарда Каина', 'Cain''s Sandals');
s := srep(s, 'Китобойные сапоги капитана Кримсона', 'Captain Crimson''s Whalers');
s := srep(s, 'Рыбацкие сапоги Боджа', 'Boj Anglers');
s := srep(s, 'Пропащие ребята', 'Lost Boys');
s := srep(s, 'Следы Аширы', 'Asheara''s Tracks');
s := srep(s, 'Огнеупорные сапоги', 'Fire Walkers');
s := srep(s, 'Сапоги для путешествий мудреца', 'Sage''s Journey');
s := srep(s, 'Сапоги для хождения по льду', 'Ice Climbers');
s := srep(s, 'Кровавые следы Наталии', 'Natalya''s Bloody Footprints');
s := srep(s, 'Путь Зунимассы', 'Zunimassa''s Trail');
s := srep(s, 'Шаги бессмертного короля', 'Immortal King''s Stride');
s := srep(s, 'Шпоры Блекторна', 'Blackthorne''s Spurs');
s := srep(s, 'Покровительство лунного света', 'Moonlight Ward');
s := srep(s, 'Ожерелье Попрыгушки', 'Squirt''s Necklace');
s := srep(s, 'Глаз Этлиха', 'Eye of Etlich');
s := srep(s, 'Медальон Рондала', 'Rondal''s Locket');
s := srep(s, 'Талисман Араноха', 'Talisman of Aranoch');
s := srep(s, 'Священная путеводная звезда', 'Holy Beacon');
s := srep(s, 'Дух времени', 'The Flavor of Time');
s := srep(s, 'Золото Кимбо', 'Kymbo''s Gold');
s := srep(s, 'Звезда Азкаранта', 'The Star of Azkaranth');
s := srep(s, 'Уроборос', 'Ouroboros');
s := srep(s, 'Амулет Ксефирии', 'Xephirian Amulet');
s := srep(s, 'Калейдоскоп Мары', 'Mara''s Kaleidoscope');
s := srep(s, 'Данкрейгский крест Блекторна', 'Blackthorne''s Duncraig Cross');
s := srep(s, 'Знак странника', 'The Traveler''s Pledge');
s := srep(s, 'Преданность Тал Раши', 'Tal Rasha''s Allegiance');
s := srep(s, 'Печатка Леорика', 'Leoric''s Signet');
s := srep(s, 'Исцеление Манальда', 'Manald Heal');
s := srep(s, 'Украденное кольцо', 'Stolen Ring');
s := srep(s, 'Кольцо Найджела', 'Nagelring');
s := srep(s, 'Кольцо нераскрытых тайн', 'Band of Untold Secrets');
s := srep(s, 'Нарушенные обещания', 'Broken Promises');
s := srep(s, 'Кольцо-головоломка', 'Puzzle Ring');
s := srep(s, 'Свет справедливости', 'Justice Lantern');
s := srep(s, 'Обсидиановое кольцо зодиака', 'Obsidian Ring of the Zodiac');
s := srep(s, 'Вечный союз', 'Eternal Union');
s := srep(s, 'Обручальное кольцо Бул-Катоса', 'Bul-Kathos''s Wedding Band');
s := srep(s, 'Кольцо глухого шепота', 'Band of Hollow Whispers');
s := srep(s, 'Перстень-череп', 'Skull Grasp');
s := srep(s, 'Печать иерофанта', 'Hierophant''s Seal');
s := srep(s, 'Единство', 'Unity');
s := srep(s, 'Иорданов камень', 'Stone of Jordan');
s := srep(s, 'Перстень-око', 'Oculus Ring');
s := srep(s, 'Литания неустрашимого', 'Litany of the Undaunted');
s := srep(s, 'Пристанище скорбных криков', 'The Wailing Host');
s := srep(s, 'Размышления Наталии', 'Natalya''s Reflection');
s := srep(s, 'Роза ветров', 'The Compass Rose');
s := srep(s, 'Сыпь Зунимассы', 'Zunimassa''s Pox');
s := srep(s, 'Ищущие грех', 'Sin Seekers');
s := srep(s, 'Гордость стрелодела', 'Fletcher''s Pride');
s := srep(s, 'Колчан серебряных звезд', 'Silver Star Piercers');
s := srep(s, 'Стрелы Света', 'Holy Point Shot');
s := srep(s, 'Стрелы с кремневыми наконечниками', 'Flint Ripper Arrowheads');
s := srep(s, 'Черные костяные стрелы', 'Black Bone Arrows');
s := srep(s, 'Наследие мертвеца', 'Dead Man''s Legacy');
s := srep(s, 'Взгляд смерти', 'Gazing Demise');
s := srep(s, 'Горечь', 'Bitterness');
s := srep(s, 'Гомункул', 'Homunculus');
s := srep(s, 'Нечто из глубин', 'Thing of the Deep');
s := srep(s, 'Ухкапианский змей', 'Uhkapian Serpent');
s := srep(s, 'Окровавленный фетиш Манаджумы', 'Manajuma''s Gory Fetch');
s := srep(s, 'Черепа Зунимассы', 'Zunimassa''s String of Skulls');
s := srep(s, 'Зимний ветер', 'Winter Flurry');
s := srep(s, 'Сингулярность', 'Singularity');
s := srep(s, 'Триумвират', 'Triumvirate');
s := srep(s, 'Око', 'The Oculus');
s := srep(s, 'Пристальный взгляд Тал Раши', 'Tal Rasha''s Unwavering Glare');
s := srep(s, 'Сила Чантодо', 'Chantodo''s Force');
s := srep(s, 'Сын Одина', 'Odyn Son');
s := srep(s, 'Орехокол', 'Nutcracker');
s := srep(s, 'Рука Телрандена', 'Telranden''s Hand');
s := srep(s, 'Ногтекус', 'Nailbiter');
s := srep(s, 'Сотрясатель земли', 'Earthshatter');
s := srep(s, 'Отголосок ярости', 'Echoing Fury');
s := srep(s, 'Хранитель солнца', 'Sun Keeper');
s := srep(s, 'Брадобрей', 'The Barber');
s := srep(s, 'Свинорез', 'Pig Sticker');
s := srep(s, 'Душегуб', 'Kill');
s := srep(s, 'Клинок кровавой магии', 'Blood-Magic Blade');
s := srep(s, 'Чародейский шип', 'Wizardspike');
s := srep(s, 'Резное копье', 'Scrimshaw');
s := srep(s, 'Арреатский закон', 'Arreat''s Law');
s := srep(s, 'Трехсотое копье', 'The Three Hundredth Spear');
s := srep(s, 'Заоблачный вестник', 'Empyrean Messenger');
s := srep(s, 'Обжигающая злость Борна', 'Born''s Searing Spite');
s := srep(s, 'Охотник на монстров', 'Monster Hunter');
s := srep(s, 'Девственный лес', 'Wildwood');
s := srep(s, 'Древняя костяная сабля Зумакалиса', 'The Ancient Bonesaber of Zumakalis');
s := srep(s, 'Вестник Рока', 'Doombringer');
s := srep(s, 'Рассекатель небес', 'Skycutter');
s := srep(s, 'Шедевр Гризвольда', 'Griswold''s Masterpiece');
s := srep(s, 'Разрубатель', 'Sever');
s := srep(s, 'Лазурная ярость', 'Azurewrath');
s := srep(s, 'Язык дьявола', 'Devil Tongue');
s := srep(s, 'Гендзанику', 'Genzaniku');
s := srep(s, 'Клин', 'The Wedge');
s := srep(s, 'Разрыватель плоти', 'Flesh Tearer');
s := srep(s, 'Крюк Мясника', 'The Butcher''s Sickle');
s := srep(s, 'Пылающий топор Санкиса', 'The Burning Axe of Sankis');
s := srep(s, 'Священный шторм', 'Hallowed Storm');
s := srep(s, 'Раскалыватель небес', 'Sky Splitter');
s := srep(s, 'Прорубатель фьордов', 'Fjord Cutter');
s := srep(s, 'Гордость Амбо', 'Ambo''s Pride');
s := srep(s, 'Луна Урожая', 'Harvest Moon');
s := srep(s, 'Священная расплата', 'Hallowed Reckoning');
s := srep(s, 'Клинок полководца', 'Blade of the Warlord');
s := srep(s, 'Кровь воина Бул-Катоса', 'Bul-Kathos''s Warrior Blood');
s := srep(s, 'Торжественная клятва Бул-Катоса', 'Bul-Kathos''s Solemn Vow');
s := srep(s, 'Удар безумия', 'Rabid Strike');
s := srep(s, 'Терзатель плоти', 'Fleshrake');
s := srep(s, 'Шраморез', 'Scarbringer');
s := srep(s, 'Кулак-кувалда', 'Sledge fist');
s := srep(s, 'Рука демона', 'Demon Hand');
s := srep(s, 'Коготь Логана', 'Logan''s Claw');
s := srep(s, 'Вон Ким Лау', 'Won Khim Lau');
s := srep(s, 'Священная длань', 'Hallowed Hand');
s := srep(s, 'Кулак Аз''Турраска', 'The Fist of Az''Turrasq');
s := srep(s, 'Хрустальный кулак', 'Crystal Fist');
s := srep(s, 'Безжалостный натиск Шэньлуна', 'Shenlong''s Relentless Assault');
s := srep(s, 'Легендарный кулак Шэньлуна', 'Shenlong''s Fist of Legend');
s := srep(s, 'Убийца луны', 'Moon Slayer');
s := srep(s, 'Клятва тени', 'Umbral Oath');
s := srep(s, 'Зуб зиккурата', 'Ziggurat Tooth');
s := srep(s, 'Лезвие Анессази', 'Anessazi Edge');
s := srep(s, 'Гидбинн', 'The Gidbinn');
s := srep(s, 'Священное спасение', 'Hallowed Salvation');
s := srep(s, 'Последний вздох', 'Last Breath');
s := srep(s, 'Нож Манаджумы для резки мяса', 'Manajuma''s Carving Knife');
s := srep(s, 'Костолом', 'Boneshatter');
s := srep(s, 'Смертоносный дробитель', 'Crushbane');
s := srep(s, 'Гнев костяного короля', 'Wrath of the Bone King');
s := srep(s, 'Небесный страж', 'Skywarden');
s := srep(s, 'Катаклизм', 'Cataclysm');
s := srep(s, 'Молот Атскеленга', 'Sledge of Athskeleng');
s := srep(s, 'Шеферский молот', 'Schaefers''s Hammer');
s := srep(s, 'Дар Калдея', 'Pledge of Caldeum');
s := srep(s, 'Осада', 'Standoff');
s := srep(s, 'Сердцекол', 'Heart Slaughter');
s := srep(s, 'Бдительность', 'Vigilance');
s := srep(s, 'Цвайхандер', 'The Zweihander');
s := srep(s, 'Верная память', 'Faithful Memory');
s := srep(s, 'Плеть', 'Scourge');
s := srep(s, 'Черный страж', 'Blackguard');
s := srep(s, 'Султан слепящих песков', 'The Sultan of Blinding Sand');
s := srep(s, 'Клинок пророчества', 'Blade of Prophecy');
s := srep(s, 'Разжигатель войны', 'Warmonger');
s := srep(s, 'Максимус', 'Maximus');
s := srep(s, 'Предок', 'The Grandfather');
s := srep(s, 'Осенний зов', 'Autumn''s Call');
s := srep(s, 'Волхв', 'The Magi');
s := srep(s, 'Сломанный посох', 'The Broken Staff');
s := srep(s, 'Средоточие Малота', 'Maloth''s Focus');
s := srep(s, 'Полынь', 'Wormwood');
s := srep(s, 'Мучитель', 'The Tormentor');
s := srep(s, 'Великий визирь', 'The Grand Vizier');
s := srep(s, 'Палач', 'The Executioner');
s := srep(s, 'Разделочный нож Мясника', 'Butcher''s Carver');
s := srep(s, 'Похититель Мессершмитта', 'Messerschmidt''s Reaver');
s := srep(s, 'Пылающая головня', 'Fire Brand');
s := srep(s, 'Презрение', 'Skorn');
s := srep(s, 'Равновесие', 'Balance');
s := srep(s, 'Тайцзи Ляй Юи', 'Lai Yui''s Taiji');
s := srep(s, 'Луна на облачном небе', 'The Clouds and the Moon');
s := srep(s, 'Весло', 'The Paddle');
s := srep(s, 'Посох Розпедина', 'Rozpedin''s Staff');
s := srep(s, 'Летящий дракон', 'Flying Dragon');
s := srep(s, 'Чертог Инны', 'Inna''s Reach');
s := srep(s, 'Бесконечная война', 'Unending War');
s := srep(s, 'Почет Бастиона', 'Bastion''s Revered');
s := srep(s, 'Молоток правосудия', 'The Gavel of Judgment');
s := srep(s, 'Ярость исчезнувшей вершины', 'Fury of the Vanished Peak');
s := srep(s, 'Разбиватель валунов бессмертного короля', 'Immortal King''s Boulder Breaker');
s := srep(s, 'Бакканский стреломет', 'Bakkan Caster');
s := srep(s, 'Орудие демона', 'Demon Machine');
s := srep(s, 'Буриза-до кэнону', 'Buriza-Do Kyanon');
s := srep(s, 'Звездная игла', 'Starspine');
s := srep(s, 'Гноестрел', 'Pus Spitter');
s := srep(s, 'Адский пригвоздитель', 'Hellrack');
s := srep(s, 'Мантикора', 'Manticore');
s := srep(s, 'Усканг', 'Uskang');
s := srep(s, 'Дальнострел', 'Longshot');
s := srep(s, 'Крыло ворона', 'The Raven''s Wing');
s := srep(s, 'Этрай', 'Etrayu');
s := srep(s, 'Дурной глаз', 'Cluckeye');
s := srep(s, 'Ядострел', 'Venomhusk');
s := srep(s, 'Сила ветра', 'Windforce');
s := srep(s, 'Звездный огонь', 'Starfire');
s := srep(s, 'Ключ Чернорука', 'Blackhand Key');
s := srep(s, 'Жест Орфея', 'Gesture of Orpheus');
s := srep(s, 'Элемент судьбы', 'Fragment of Destiny');
s := srep(s, 'Пылающие руины', 'Ruinstoke');
s := srep(s, 'Священный скипетр', 'Hallowed Scepter');
s := srep(s, 'Безумие Слорака', 'Slorak''s Madness');
s := srep(s, 'Воля Чантодо', 'Chantodo''s Will');
s := srep(s, 'Меткий стрелок', 'Deadeye');
s := srep(s, 'Иззукуб', 'Izzuccob');
s := srep(s, 'Арбалет погребального костра', 'Balefire Caster');
s := srep(s, 'Утренняя заря', 'Dawn');
s := srep(s, 'Священный вердикт', 'Hallowed Judgment');
s := srep(s, 'Катастрофа', 'Calamity');
s := srep(s, 'Злость Данетты', 'Danetta''s Spite');
s := srep(s, 'Месть Данетты', 'Danetta''s Revenge');
s := srep(s, 'Убийственный арбалет Наталии', 'Natalya''s Slayer');
result := s;
end;



Function translate_type(s3:string):string;
begin
 s3 := StringReplace(s3, 'Магическая', 'Magic', []);
    s3 := StringReplace(s3, 'Магический', 'Magic', []);
    s3 := StringReplace(s3, 'Магическое', 'Magic', []);
    s3 := StringReplace(s3, 'Магические', 'Magic', []);
    s3 := StringReplace(s3, 'Редкая', 'Rare', []);
    s3 := StringReplace(s3, 'Редкий', 'Rare', []);
    s3 := StringReplace(s3, 'Редкое', 'Rare', []);
    s3 := StringReplace(s3, 'Редкие', 'Rare', []);
    s3 := StringReplace(s3, 'Комплектная', 'Set', []);
    s3 := StringReplace(s3, 'Комплектный', 'Set', []);
    s3 := StringReplace(s3, 'Комплектное', 'Set', []);
    s3 := StringReplace(s3, 'Комплектные', 'Set', []);
    s3 := StringReplace(s3, 'Легендарная', 'Legendary', []);
    s3 := StringReplace(s3, 'Легендарный', 'Legendary', []);
    s3 := StringReplace(s3, 'Легендарное', 'Legendary', []);
    s3 := StringReplace(s3, 'Легендарные', 'Legendary', []);



    s3 := StringReplace(s3, 'предмет заклинательницы', 'Enchantress Focus', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'талисман негодяя', 'Scoundrel Token', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'реликвия храмовника', 'Templar Relic', [rfReplaceAll, rfIgnoreCase]);




    s3 := StringReplace(s3, 'Кистевое оружие', 'Fist weapon', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Церемониальный нож', 'Ceremonial Knife', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Мощное оружие', 'Mighty Weapon', [rfReplaceAll, rfIgnoreCase]);


    s3 := StringReplace(s3, 'Двуручная булава', 'Two-Handed Mace', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Древковое оружие', 'Polearm', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Двуручный меч', 'Two-Handed Sword', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Двуручный топор', 'Two-Handed Axe', []);
    s3 := StringReplace(s3, 'Мощное двуручное оружие', 'Two-Handed Mighty Weapon', []);
    s3 := StringReplace(s3, 'Ручной арбалет', 'Hand Crossbow', [rfReplaceAll, rfIgnoreCase]);


    s3 := StringReplace(s3, 'духовный камень', 'Spirit Stone', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Шлем', 'Helm', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Маска вуду', 'Voodoo mask', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Шляпа чародея', 'Wizard Hat', [rfReplaceAll, rfIgnoreCase]);


    s3 := StringReplace(s3, 'Самоцвет', 'Gem', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Краска', 'Dye', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Зелье', 'Potion', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Материалы', 'Crafting Material', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Эскиз кузнеца', 'Blacksmith Plan', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Эскиз ювелира', 'Jeweler Design', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'мощный пояс', 'Mighty Belt', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'нагрудный доспех', 'Chest Armor', [rfReplaceAll, rfIgnoreCase]);

    s3 := StringReplace(s3, 'наплечники', 'Shoulders', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'амулет', 'Amulet', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'перчатки', 'Gloves', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Плащ', 'Cloak', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'наручи', 'Bracers', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'кольцо', 'Ring', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'ножная броня', 'Pants', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'обувь', 'Boots', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Пояс', 'Belt', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'щит', 'Shield', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'сфера', 'Source', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'оберег', 'Mojo', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'колчан', 'Quiver', [rfReplaceAll, rfIgnoreCase]);

    s3 := StringReplace(s3, 'Посох', 'Staff', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Дайбо', 'Daibo', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Булава', 'Mace', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'кинжал', 'Dagger', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Копье', 'Spear', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Меч', 'Sword', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'топор', 'Axe', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Лук', 'Staff', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Арбалет', 'Crossbow', [rfReplaceAll, rfIgnoreCase]);
    s3 := StringReplace(s3, 'Жезл', 'Wand', [rfReplaceAll, rfIgnoreCase]);
    result := s3;
end;

Function translate_slot(s3:string):string;
begin
  s3 := StringReplace(s3, 'Голова', 'Head', []);
        s3 := StringReplace(s3, 'Плечи', 'Shoulders', []);
        s3 := StringReplace(s3, 'Шея', 'Neck', []);
        s3 := StringReplace(s3, 'Руки', 'Hands', []);
        s3 := StringReplace(s3, 'Корпус', 'Torso', []);
        s3 := StringReplace(s3, 'Запястья', 'Wrists', []);
        s3 := StringReplace(s3, 'Палец', 'Finger', []);
        s3 := StringReplace(s3, 'Пояс', 'Waist', []);
        s3 := StringReplace(s3, 'Ноги', 'Legs', []);
        s3 := StringReplace(s3, 'Ступни', 'Feet', []);
        s3 := StringReplace(s3, 'Одноручное оружие', '1-Hand', []);
        s3 := StringReplace(s3, 'Левая рука', 'Off-Hand', []);
        s3 := StringReplace(s3, 'Двуручное оружие', '2-Hand', []);
        s3 := StringReplace(s3, 'Спутник', 'Follower', []);
  result := s3;

end;

end.
